### ISSUE TITLE
2주차 TODO

### ISSUE THREAD

**Issue by jkl851** [fe-sailor/sevingu#4]
모두🦊 🐼 🐹 🐰
- [ ] : 상태값 구상
- [ ] : Config

민철🦊
- [ ] : undo & redo

요한🐼
- [ ] : 메인 뷰어 

진식🐹
- [ ] : 코어 로직 연결

수연🐰
- [ ] : 다이얼로그 작업
- [ ] : 구글 광고 붙이기 찾아보기 & 다운로드
- [x] : config UI 구성요소 TODO 리스트로 정리
